== Recipe: Seminola Pudding

This is a sweet Pudding, very simple and sweet. Made like my grandma did.

== Ingredients

* 500 ml milk
* 75 g seminola
* 50 g sugar
* 8 g Vanilla sugar (1 package)
* some salt for taste

== Preparation

Fill the milk into a pot.
Mix sugar and Vanilla sugar and stir it into the milk. 
Heat the milk and bring it to a boil.

Remove the pot from the heat and wait a moment until the milk goes down. +
Now slowly drizzle the seminola into the milk and bring it to a boil again. +
Stir it permanently.

!!! If you bring the seminola in a boiling liquid the seminola will make lumps.

Remove the pot from the heat and wait 3 minutes. The seminola must swell now. +
Stir it occasionally.

After 3 minutes you can eat it as a sweet soup or you can fill it into a mold 
and cool it down and make a pudding. +
Do not cover the mold or your pudding will NOT get hard.

You can add some cinnamon, if you like.

Garnish the pudding with some fruits. Stewed fruits like apple purree, stewed 
plums or stewd pears perfectly fits this pudding.
