= Recipe: Pizza 

This recipe is divided into multiple parts. Each part has its own head line.

== Dough

Pizza dough is one of the simplest dough you can have. It contains 

* 200 ml water
* 303 g flour (Type 550 wheat or Type 630 spelt)
* 10 g olive oil
* 5 g salt
* 7 g dried yeast +
  or 
* 25 g fresh yeast +
  or 
* 100 g sourdough

If you use sourdough, mix your highly active sourdough in water until 
completely solved. +
If using yeast, mix it with warm water and a tea spoon honey or sugar.

Mix water with flour and wait 30 minutes.

Add olive oil and salt. Mix it with the dough. +
Knead your dough ca. 10 min with a kitchen machine or a hand mixer. +
Your dough is in right condition if you can stretch it like a gum and the dough
wants to form a ball.

Your dough must stay in a covered bowl at a "warm" place. Warm means a 
temperature between 18 and 30 °C. +
Wait 2 - 3 hours if you use yeast. And 5 - 6 hours if using sourdough. +
Time is shorter if temperature is higher. +
The dough is good if it is blown up or little gas bubbles ar on the top.

Carefully remove the dough from your bowl on a working plate covered with 
flour. Put flour on your hands and stretch and fold the dough multiple times
until the dough feels strong. +
Put the dough on your pizza form or on a backing tray. Roll it out thin.


== Pizza Sauce

You need:

* 2 Tomatos, sliced
* 2 table spoon Olive Oil
* 1 table spoon concentrated Tomato paste
* herb mixture
** 1 tea spoon Oregano
** 1 tea Spoon sage
** 1/2 tea spoon Thym
** 1/2 tea spoon Basil

Put herbs in a mortar and ground them with a pestle. +
Add all in a small cup and mix it to a liquid paste with a food processor or 
blender.
