= Recipe: Pumpkin Soup

This recipe makes a soup for 4 - 6 dishes.

== Ingredients

* Pumpkin 1 - 1.5 kg (Hokkaido, Butternut ... )
* olive oil
* 1 Onion, coarsly chopped into cubes
* 1 or 2 cloves Garlic, finely chopped (optional)
* 1 can coconut milk (ca. 400ml)
* 1 or 2 red Chili, finely chopped (optional, to taste)
* ca 500g mixed vegetables for soups consisting of
** carrots
** green peas
** green garden beans
** celery root
** leek
* salt and pepper to taste

== Preparing the Pumpkin

Pumpkins with softer skin, like Hokkaido or Butternut, do not need to be 
peeled. If you do not like the skin, remove it. If you do not care about the 
skin, clean the Pumpkin well before cutting. +
Cut the Pumpkin with a long, sharp knife into 2 parts. Remove the seeds with 
a table spoon. +
Cut the Pumpkin into cubes, ca. 1.5 - 2 cm. It is not necessary to make them 
exactly the same size. It is just to reduce the cooking time.

== Cooking

In a big pot add enough oil to cover the floor and heat oil over medium heat. +
Add onions and cook, stirring until onions are soft and glazy for 5 min.

Add roughly the half of the Pumpkin cubes and Garlic if used and cook it until 
Pumpkin cubes start to get softer. Cook them for ca. 5 min, stirring 
occassionally.

Add the rest of the Pumpkins, coconut milk, vegetables and chili, if used. 
You should have added enough Coconut Milk to fill up the Pot until 1 or 2 cm 
less than the Pumpkin cubes. You can add some water if necessary. Heat it up 
and bring it to a boil. +
Reduce heat and simmer for 20 minutes. Stir it occasionally.

After 20 minutes the Pumpkins should be soft. Stir the soup for 2 - 5 min 
with low heat. The Pumpkin cubes should dissolve and thicken the soup. +
You also can use a food processor to mashit. But a food processor also mashes
the vegetables and make it one single colored soup.

Serve it garnished with a splotch of fresh youghurt.

