= Recipe: Heaven and Earth

This recipe describes howto make a dish called "Heaven and Earth". It 
contains Apples (Heaven) and Potatos (Earth).

== You need

* Potatos and Apples (can be sour), weighted 1:1
* 1 medium Onion, squared (or 2 small)
* 1 or 2 toes garlic, finely chopped (optional)
* Oil or Bacon squares
* Water
* 1 Teaspoon Cinnamon
* Salt, 1 pinch
* 1 Teaspoon Curry (optional)


== Preparing

Prepare potatos the same way you want to cook them in salted water. You 
can let the peel on it if you have new potatos with thin peel. +
Cut the apples into quarters or eights and remove the core in the middle. 
You can leave the peel on the apple pieces.

Cut the onion into squares. +
Finely chop the garlic.


== Cooking

Heat oil or Bacon in a big pot to medium heat. If you use Bacon, let the 
fat out until it the squares look transparent. +
Add onions and cook stirring for 5 min or until soft. Add garlic if used 
and cook stirring for 1 minute. +
Now add potatos and apples. Add salt, cinnamon and curry powder as you 
want. It can smell like christmas apples - it is okay.  +
Fill up with water until covered. +
Stirr all to mix it well.

Heat up and bring it to a boil. Reduce heat and cook it slightly for 
20 minutes.

The dish is ready when apples and potatos are soft. Potatos should fall from 
a fork and apples should be soft and start to disolve in water if stirred 
around. +
Use a potato masher or a mixer/food processor to produce a thick mash.

