= Recipe: Heaven and Earth

This recipe describes howto make a dish called "Heaven and Earth". It 
contains Apples (Heaven) and Potatos (Earth).

== You need

* Potatos
* Apples (can be sour)
* 1 medium Onion, squared (or 2 small)
* 1 or 2 garlic, finely chopped (optional)
* Oil or Bacon squares
* Water
* Cinnamon
* Salt
* Curry (optional)


== Preparing

Prepare potatos the same way you would cook them in water. You can let the
peel if you have new potatos with thin peel. +
Cut the apples into quarters or eights and remove the core in the middle. 
You can leave the peel on the apple pieces.

Cut the onion into squares. +
Finely chop the garlic.


== Cooking

Heat oil or Bacon in a big pot to medium heat. If you use Bacon, let the 
fat out. +
Add onions and cook stirring for 5 min or until soft. Add garlic if used 
and cook stirring for short time. +
Now add potatos and apples. Add cinnamon and curry powder for taste. It 
can smell like christmas apples it is okay.  +
Fill up with water until covered. +
Stirr all to mix it well.

Heat up and bring it to a boil. Reduce heat and let it cook for 20 minutes.

The dish is ready when apples and potatos are soft. Potatos should fall from 
a fork and apples should be soft and disolve in water if stirred around. +
Use a potato masher or a mixer/food processor to make a thick mash.

