= Recipe: Banana Bread

This recipe describes howto make a Banana Bread.

== You need

* Baking form for bread, 25 cm long
* baking sheet or butter and breadcrumbs

* 375g ripe Bananas (weighted WITH peel)
* 225g sugar
* 1 package Vanilla sugar (8g)
* 1/4 Teaspoon Salt (ca. 1g, optional)
* 2 eggs (optional)
* 100g Sour Dough (optional)
* 250g Flour (all purpose, whole grain, Type 550, all is fine)
* 1/2 package baking powder (ca. 7g) (double it if you ommit the eggs)
* 100g Oil (Olive, rapeseed, sunflower, all is fine)
* 70g Milk (or plant based milk)

== Making the Dough

Heat the oven to 175°C. Prepare your form with the baking sheet or with 
butter and breadcrumbs.

Peel the bananas and mash them with a mixer or a fork in a big bowl. Mix the 
Vanilla sugar with sugar and mix both into the banana mash. Stir or mix until 
the sugar disappered in the banana mash. The sugar must be completely solved 
in the mash. You can test with your mouth. If you do not feel the sugar 
crystals on your tongue it is good.   
Add eggs and salt if you use it and mix it well.   
Add sour dough - if you use it -, oil and milk. Mix it well.

Mix baking powder with flour. Than mix the flour slowly under the banana and 
sugar mash. Add only so many flour as it can be disolved. Not all at once - it 
will make lumps - like making semolina or polenta. Mix all well until you have 
a smooth and semifluid dough.


== Baking and Cooling

Fill the dough in your form. Place the form in the oven - middle level.   
Bake it for 60 minutes or until no dough stick on a wooden stick.

Take the Banana Bread out of the oven and wait 10 - 20 minutes. Put it out of 
the form on a cooling rack for cakes and let it cool down (maybe 20 - 40 
minutes).
